// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Client documents
 */
interface ClientDocumentData {
  /**
   * Client field in *Client*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of client
   * - **API ID Path**: client.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client: prismic.KeyTextField;
}

/**
 * Client document from Prismic
 *
 * - **API ID**: `client`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientDocumentData>,
    "client",
    Lang
  >;

/**
 * Item in *Projects → Project Tasks*
 */
export interface ProjectsDocumentDataProjectTasksItem {
  /**
   * Tasks field in *Projects → Project Tasks*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Tasks?
   * - **API ID Path**: projects."project-tasks"[].tasks
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tasks: prismic.ContentRelationshipField<"tasks">;
}

/**
 * Item in *Projects → Project Skills*
 */
export interface ProjectsDocumentDataProjectSkillsItem {
  /**
   * Skills field in *Projects → Project Skills*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Skill?
   * - **API ID Path**: projects.project_skills[].skills
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  skills: prismic.ContentRelationshipField<"skills">;
}

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Title field in *Projects*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Abbreviation field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.abbreviation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  abbreviation: prismic.KeyTextField;

  /**
   * Description field in *Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Testing this field in *Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.testing_this
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testing_this: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Type field in *Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: SELECT TYPE
   * - **API ID Path**: projects.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  type: prismic.ContentRelationshipField<"type">;

  /**
   * Year field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What years did you work on this?
   * - **API ID Path**: projects.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * Website Link field in *Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link?
   * - **API ID Path**: projects.website_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Link field in *Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Another link?
   * - **API ID Path**: projects.secondary_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Client field in *Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Client worked with?
   * - **API ID Path**: projects.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  client: prismic.ContentRelationshipField<"client">;

  /**
   * Studio field in *Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Studio worked with?
   * - **API ID Path**: projects.studio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  studio: prismic.ContentRelationshipField<"studio">;

  /**
   * Project Tasks field in *Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.project-tasks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  "project-tasks": prismic.GroupField<
    Simplify<ProjectsDocumentDataProjectTasksItem>
  >;

  /**
   * Project Skills field in *Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.project_skills[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_skills: prismic.GroupField<
    Simplify<ProjectsDocumentDataProjectSkillsItem>
  >;

  /**
   * Dip ID field in *Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Display ID?
   * - **API ID Path**: projects.dip_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  dip_id: prismic.NumberField;

  /**
   * Gallery Count field in *Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Gallery Count
   * - **API ID Path**: projects.gallery_count
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  gallery_count: prismic.NumberField;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Content for Skills documents
 */
interface SkillsDocumentData {
  /**
   * Name field in *Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add skill here
   * - **API ID Path**: skills.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SkillsDocumentData>,
    "skills",
    Lang
  >;

/**
 * Content for Studio documents
 */
interface StudioDocumentData {
  /**
   * Name field in *Studio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add studio name
   * - **API ID Path**: studio.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Studio document from Prismic
 *
 * - **API ID**: `studio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StudioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StudioDocumentData>,
    "studio",
    Lang
  >;

/**
 * Content for Tasks documents
 */
interface TasksDocumentData {
  /**
   * Name field in *Tasks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add task here
   * - **API ID Path**: tasks.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Tasks document from Prismic
 *
 * - **API ID**: `tasks`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TasksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TasksDocumentData>, "tasks", Lang>;

/**
 * Content for Type documents
 */
interface TypeDocumentData {
  /**
   * Name field in *Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add type here
   * - **API ID Path**: type.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Type document from Prismic
 *
 * - **API ID**: `type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TypeDocumentData>, "type", Lang>;

export type AllDocumentTypes =
  | ClientDocument
  | ProjectsDocument
  | SkillsDocument
  | StudioDocument
  | TasksDocument
  | TypeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ClientDocument,
      ClientDocumentData,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataProjectTasksItem,
      ProjectsDocumentDataProjectSkillsItem,
      SkillsDocument,
      SkillsDocumentData,
      StudioDocument,
      StudioDocumentData,
      TasksDocument,
      TasksDocumentData,
      TypeDocument,
      TypeDocumentData,
      AllDocumentTypes,
    };
  }
}
